spring:
  application:
    name: learn-reactivespring

app:
  r2dbc:
    postgres:
      url: r2dbc:postgresql://localhost/ordersDb
      username: postgres
      password: postgres

    mysql:
      url: r2dbc:mysql://localhost/customersdb
      username: root
      password: root

cron:
  generate: "*/10 * * * * *"