spring:
  application:
    name: learn-reactivespring

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true

app:
  r2dbc:
    postgres:
      url: r2dbc:postgresql://localhost/ordersDb
      username: postgres
      password: postgres

    mysql:
      url: r2dbc:mysql://localhost/customersdb
      username: root
      password: 1234

logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: DEBUG

cron:
  generate: "*/10 * * * * *"

queue:
  orders: order-queue