spring:
  application:
    name: learn-reactivespring

app:
  r2dbc:
    postgres:
      url: r2dbc:postgresql://localhost/ordersDb
      username: postgres
      password: postgres

    mysql:
      url: r2dbc:mysql://localhost/customersdb
      username: root
      password: 1234

logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: DEBUG

cron:
  generate: "*/10 * * * * *"